// Generated by gencpp from file control_pkg/servo_controlResponse.msg
// DO NOT EDIT!


#ifndef CONTROL_PKG_MESSAGE_SERVO_CONTROLRESPONSE_H
#define CONTROL_PKG_MESSAGE_SERVO_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_pkg
{
template <class ContainerAllocator>
struct servo_controlResponse_
{
  typedef servo_controlResponse_<ContainerAllocator> Type;

  servo_controlResponse_()
    : angle(0.0)  {
    }
  servo_controlResponse_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::control_pkg::servo_controlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_pkg::servo_controlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct servo_controlResponse_

typedef ::control_pkg::servo_controlResponse_<std::allocator<void> > servo_controlResponse;

typedef boost::shared_ptr< ::control_pkg::servo_controlResponse > servo_controlResponsePtr;
typedef boost::shared_ptr< ::control_pkg::servo_controlResponse const> servo_controlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_pkg::servo_controlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_pkg::servo_controlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_pkg::servo_controlResponse_<ContainerAllocator1> & lhs, const ::control_pkg::servo_controlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_pkg::servo_controlResponse_<ContainerAllocator1> & lhs, const ::control_pkg::servo_controlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_pkg::servo_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_pkg::servo_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_pkg::servo_controlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::control_pkg::servo_controlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_pkg/servo_controlResponse";
  }

  static const char* value(const ::control_pkg::servo_controlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
;
  }

  static const char* value(const ::control_pkg::servo_controlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_controlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_pkg::servo_controlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_pkg::servo_controlResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_PKG_MESSAGE_SERVO_CONTROLRESPONSE_H
